### ISSUE TITLE
Documentation fault

### ISSUE THREAD

**Issue by HaraldPlatz** [davidwaterston/goto-matching-bracket#11]
Related to version 2.1.0 of matching brackets extension.

To add an own short-cut-key the current documentation says 

> This is done using the Debug... Open User Key Map menu item and adding in a new entry like this in > the overrides section:
> "Cmd-Shift-Z": "davidwaterston.goto-matching-bracket.findMatch" 

If you try this and you got the hint 
![image](https://cloud.githubusercontent.com/assets/12428480/12235586/fd6677b0-b874-11e5-8ec0-976f3271b8dc.png)
 (sorry for the german text)  from brackets editor try this:

```
"overrides": {
  "Ctrl-e": "davidwaterston.goToMatchingBracket.findMatch"
}
```

The correct command could be found in main.js function init().

**Comment by davidwaterston** [comment]
@HaraldPlatz Thanks for the bug report. That must have been missed in the last refactor I did.
I'll fix it tonight.
