### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by PhiLhoSoft** [davidwaterston/goto-matching-bracket#5]
Several translations are possible for this "Go to Matching Bracket" sentence.
I saw in an editor "Apparier le symbole", but it is a bit esoteric.

So I propose to translate to "Aller au symbole correspondant", ie. go to corresponding / matching symbol, as French doesn't have a generic term for "bracket" (some consider "brace" to be more generic, a debate I won't enter in...).

Side note: even if I know the value of the charsToMatch map isn't used, I find disturbing that the value of "(" is ")" (unlike the other values). Or, perhaps, just put a neutral char (or empty string, or boolean) there.

**Comment by davidwaterston** [comment]
@PhiLhoSoft Thanks for the updated translation, I'll make that change later today. 
I did have a native French speaker translate the original text but he wasn't very technical so the concept of a 'matching bracket' might have been confusing.

I can understand why the 'charsToMatch' map appears confusing... a neutral char might make it more obvious what is being done and why. I'll make that change later as well.

Thanks again for your input.
